// Auth
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_CLEAR = 'AUTH_CLEAR';
const AUTH_SET_USER = 'AUTH_SET_USER';

// Common Actions
const LOAD_STATUS = 'LOAD_STATUS';
const SAVE_STATUS = 'SAVE_STATUS';
const SET_META = 'SET_META';
const SET_ITEMS = 'SET_ITEMS';
const SET_ITEM = 'SET_ITEM';
const SET_FILTERS = 'SET_FILTERS';
const SET_SORTING = 'SET_SORTING';
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

// steps
const ADD_STEP = 'ADD_STEP';
const DELETE_STEPS = 'DELETE_STEPS';
const SET_IS_STEP_SELECTED = 'SET_IS_STEP_SELECTED';
const SET_ACTIVE_STEP = 'SET_ACTIVE_STEP';
const SET_STEP_VALUE = 'SET_STEP_VALUE';

//images previewer
const ADD_IMAGES = 'ADD_IMAGES';
const DELETE_IMAGE = 'DELETE_IMAGE';

// prefixes
const CLIENT_ADD_CAR_ = 'CLIENT_ADD_CAR_';
const CATALOG_FULL_ADD_GROUP_ = 'CATALOG_FULL_ADD_GROUP_';
const CATALOG_ADD_ = 'CATALOG_ADD_';
const CATALOG_ADD_MANUFACTURER_ = 'CATALOG_ADD_MANUFACTURER_';
const CATALOG_ADD_MODEL_ = 'CATALOG_ADD_MODEL_';
const CATALOG_ADD_MODIFICATION_ = 'CATALOG_ADD_MODIFICATION_';


export {
	AUTH_SUCCESS,
	AUTH_CLEAR,
	AUTH_SET_USER,
	LOAD_STATUS,
	SAVE_STATUS,
	SET_META,
	SET_ITEMS,
	SET_ITEM,
	SET_FILTERS,
	SET_SORTING,
	OPEN_MODAL,
	CLOSE_MODAL,
	ADD_STEP,
	DELETE_STEPS,
	SET_IS_STEP_SELECTED,
	SET_ACTIVE_STEP,
	SET_STEP_VALUE,
	ADD_IMAGES,
	DELETE_IMAGE,
	SET_SEARCH_QUERY,
	CLIENT_ADD_CAR_,
	CATALOG_FULL_ADD_GROUP_,
	CATALOG_ADD_,
	CATALOG_ADD_MANUFACTURER_,
	CATALOG_ADD_MODEL_,
	CATALOG_ADD_MODIFICATION_,
}
